# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 762a5a03fa8b31b2874c7355a6f08dbad45db14ea179dea9559aae9b2d0f1ae754e201d43306ff958c0218f1955fa129ff26f12130053562ae3cba50448b36de

test:
  secret_key_base: 2c667a0a8843c980c892aa14d594464ca0d94f769026a414a534e200c3177780373f3d9bcd7912ec39116a16165df5300cc018404b5fee18667aa3576b7e8a53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
